### ISSUE TITLE
Linking paper and code

### ISSUE THREAD

**Issue by adirajagopal** [ridgerchu/SpikeGPT#11]
Hi, I had a couple of questions on the paper as well as the link to the code here. 
1) Do you have any materials on how you derived of Eq.10 in the paper from Eq.4?
2) I'm also a little unclear how the CUDA function "kernel_forward" in wkv_cuda.cu implements the Eq.10 - could you provide some pointers around that please? 

Thanks!

**Comment by ridgerchu** [comment]
Hi!

For the first issue, please refer to Fig.2. In this structure, 'W' can be viewed as a convolution kernel of the same size as 'K/V', enabling convolution operations for parallel processing. We have an animation that illustrates this concept, and you can find it in this [talk record](https://intel-ncl.atlassian.net/wiki/spaces/INRC/blog/2023/05/24/1933738007/INRC+Forum+May+30th+Jason+Eshraghian+Ruijie+Zhu) between 25:00 to 28:00, where I discuss this particular problem in detail.

Regarding the second point, language models often encounter overflow issues during training. To address this, we introduced a new variable 'pp' to manage these overflow concerns. Nevertheless, the overall functionality aligns with what is described in Eq.10. For a more comprehensive explanation, please consult our RWKV [EMNLP paper](https://openreview.net/pdf?id=7SaXczaBpG), particularly Eq.23-28, where this is thoroughly discussed.
