### ISSUE TITLE
RuntimeError: Error building extension 'wkv'

### ISSUE THREAD

**Issue by Ewen-smile** [ridgerchu/SpikeGPT#4]

**Comment by ridgerchu** [comment]
Hi, I guess this error is caused by the CUDA compile, have you install the CUDA correctly?

**Comment by Ewen-smile** [comment]
I have installed CUDA11.0
<img width="308" alt="image" src="https://github.com/ridgerchu/SpikeGPT/assets/105697758/476fd2c9-ba1d-4e1e-9a16-8f7a5e820fe5">

**Comment by ridgerchu** [comment]
The building extension 'wkv' is from CUDA, could you please give me the full report of this error?

**Comment by Ewen-smile** [comment]
![QQ图片20230614123639](https://github.com/ridgerchu/SpikeGPT/assets/105697758/029803d7-85f2-47e4-86e4-ff522bda134a)

**Comment by two-tiger** [comment]
I have the same problem. And this issue occurred after I updated my cupy 
<img width="1166" alt="image" src="https://github.com/ridgerchu/SpikeGPT/assets/80751293/709dfcdc-40b5-4b52-888f-095f47c315a0">

**Comment by ridgerchu** [comment]
The wkv module is built using CUDA and requires the ninja compiler for compilation. The issue you are experiencing seems to be related to the compilation process, which can be influenced by the varying compilation environments. However, I can confirm that the problem originates from the compilation process.

**Comment by two-tiger** [comment]
I have solved this problem, just pay attention to this error message `subprocess.CalledProcessError: Command ‘[‘ninja‘, ‘-v‘]‘ returned non-zero exit status 1.` Modify `lib/python3.6/site-packages/torch/utils/cpp_extension.py` in the anaconda environment file, change `['ninja ',' - v ']` to `['ninja', '- v']` or `['ninja ',' - version ']`. I hope this will be helpful to you
