### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by haung-hangdian** [ridgerchu/SpikeGPT#5]
How the dataset is made

**Comment by ridgerchu** [comment]
Hi, you can refer to the paper of The Pile (https://arxiv.org/abs/2101.00027). We use OpenWebText2 selected from The Pile.

**Comment by haung-hangdian** [comment]
I want to know what format of file is in 'enwik8'

**Comment by ridgerchu** [comment]
Hi, sorry for confusing. it is a txt file.

**Comment by haung-hangdian** [comment]
我想知道你用的python环境和cuda，我跑train，一直说Traceback (most recent call last):
  File "/home/lab/SpikeGPT/train.py", line 94, in <module>
    model = GPT(GPTConfig(train_dataset.vocab_size, train_dataset.ctx_len, model_type=model_type,
  File "/home/lab/SpikeGPT/src/model.py", line 355, in __init__
    self.blocks = nn.Sequential(*[Block(config, i)
  File "/home/lab/SpikeGPT/src/model.py", line 355, in <listcomp>
    self.blocks = nn.Sequential(*[Block(config, i)
  File "/home/lab/SpikeGPT/src/model.py", line 316, in __init__
    self.lif1 = neuron.MultiStepLIFNode(tau=2., surrogate_function=surrogate.ATan(alpha=2.0), backend='cupy',
  File "/home/lab/SpikeGPT/src/spikingjelly/clock_driven/neuron.py", line 823, in __init__
    check_backend(backend)
  File "/home/lab/SpikeGPT/src/spikingjelly/clock_driven/neuron.py", line 30, in check_backend
    assert cupy is not None, 'CuPy is not installed! You can install it from "https://github.com/cupy/cupy".'
AssertionError: CuPy is not installed! You can install it from "https://github.com/cupy/cupy".
可是我已经安装了cuda对应版本的cupy，我用的是4090的显卡

**Comment by ridgerchu** [comment]
Hello,

We've tested multiple CUDA and cupy versions, ranging from 10.2 to 12.0. Additionally, we've experimented with PyTorch versions spanning from 1.9.0 to 2.0.0 – all of which have exhibited proper functionality. If you require additional assistance, kindly open a new issue to address your inquiries related to environment configuration, rather than commenting on this existing issue.

**Comment by haung-hangdian** [comment]
thank you

**Comment by ZiyanHuang11** [comment]
In the NLU file, can you provide the datasets mentioned in the code? And what are the format of the datasets.
