### ISSUE TITLE
Using [Vit] with SpikeGPT model 

### ISSUE THREAD

**Issue by Mohammed20201991** [ridgerchu/SpikeGPT#7]
Hello everyone , 
It is fantastic to see your great  job you have done .
Is it possible to leverage [Vit](https://huggingface.co/google/vit-base-patch16-224) model (or it can be any) for image understanding with SpikeGPT in Sequence to Sequence task for image captions task ?

**Comment by ridgerchu** [comment]
Hi Mohammed,
Yes we can leverage VIT as one of the backbone! However, SpikeGPT model only support autoregressive task now. VIT tasks are more like BERT, which based on MLM training method, may still need effort to do so...

**Comment by Mohammed20201991** [comment]
Thanks @ridgerchu , then what about possibility for integration with [TrOCR](https://huggingface.co/microsoft/trocr-large-handwritten) by replacing the decoder part on it with `SpikeGPT` model .
I think first we need to migrate it in to [HF](https://huggingface.co/) format then it could be leveraged .
Or what (is) are possible models that can be used with less effort in task such as `Image Captions`, `Image-to-text` , `Text-to-text`, and `Speech-to-text`
the idea here is to put it (or make it adaptable )in Sequence-to-Sequence Arch.

**Comment by ridgerchu** [comment]
Thanks Mohammed!

Yeah it is viable to implement to the decoder of any Transformer module (with attention masks) I'm now working on huggingface integration, hopefully it can merge into [transformer.rwkv](https://huggingface.co/docs/transformers/model_doc/rwkv)!
