### ISSUE TITLE
Access to downstream task finetuned models

### ISSUE THREAD

**Issue by adirajagopal** [ridgerchu/SpikeGPT#9]
Hi, have you open-sourced the models that you used for the perplexity values quoted in (https://arxiv.org/abs/2302.13939)? For instance do you have the wikitext-2 and wikitext-103 models open source anywhere? 

Alternatively, in order to create a custom model to reproduce those results, should I start with the provided 216M model trained on OpenWebText and finetune it on wikitext using the provided train.py script? 

Thanks!

**Comment by ridgerchu** [comment]
Hi, sorry for the fine-tuned wikitext-2 and wikitext-103, we do not save these models. If you wants to fine-tune your own model, you need to first pre-tokenize your text with [jsonl2binidx](https://github.com/Abel2076/json2binidx_tool) tool, and fine-tune it by train.py.

**Comment by adirajagopal** [comment]
Thanks!
